version: "2"
run:
  timeout: 3m
linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
formatters:
  enable:
    - gofmt
    - goimports
