package live

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/mkoziy/hermestrator/internal/dashboard"
)

// DirectExecutor invokes codex or pi directly for plan execution, skipping
// ralphex's orchestration entirely. When SelectExecutor picks Codex or Pi
// instead of Ralphex, the DirectExecutor reads the plan file generated by
// the Planner and hands it to the selected executor as a bounded execution
// task via ProcessRunner.
//
// By construction this type never invokes ralphex — callers must route
// through RalphexExecutor when the selection is Ralphex.
type DirectExecutor struct {
	// Runner executes the codex / pi binary and streams output.
	Runner *ProcessRunner
}

// Run reads the plan file from the workspace and invokes either codex exec
// or pi -p directly with the plan as the execution task. It returns the
// RunResult so callers can surface execution telemetry in the dashboard.
//
// kind must be dashboard.Codex or dashboard.Pi; any other value returns
// an error. Ralphex execution must use RalphexExecutor instead.
func (e *DirectExecutor) Run(ctx context.Context, kind dashboard.ExecutorKind, workspacePath string) (*RunResult, error) {
	if kind != dashboard.Codex && kind != dashboard.Pi {
		return nil, fmt.Errorf("direct execution: unsupported executor kind %q (only codex and pi are supported)", kind)
	}

	planPath := filepath.Join(workspacePath, dashboard.PlanFileName)
	planContent, err := os.ReadFile(planPath)
	if err != nil {
		return nil, fmt.Errorf("direct execution: read plan file: %w", err)
	}

	task := buildExecutionTask(string(planContent))
	name, args := directExecCommand(kind, task)

	runner := e.Runner
	if runner == nil {
		runner = &ProcessRunner{Command: exec.CommandContext}
	}
	result, err := runner.Run(ctx, workspacePath, nil, name, args...)
	if err != nil {
		return result, fmt.Errorf("direct execution: %w", err)
	}
	return result, nil
}

// buildExecutionTask wraps the plan content as a bounded execution task
// for the direct executor (codex or pi). The executor receives the full
// plan and is instructed to execute each task section in order.
func buildExecutionTask(planContent string) string {
	return fmt.Sprintf(
		"Execute the following plan step by step in the current workspace. "+
			"Follow each task section in order and apply the described changes.\n\n%s",
		planContent,
	)
}

// directExecCommand returns the binary name and arguments for running a
// direct execution of the plan via codex or pi.
func directExecCommand(kind dashboard.ExecutorKind, task string) (string, []string) {
	switch kind {
	case dashboard.Pi:
		return "pi", []string{"-p", task}
	default:
		return "codex", []string{"exec", task}
	}
}
